# Generated by Django 5.0.4 on 2025-04-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="message",
        ),
        migrations.AlterField(
            model_name="payment",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Registration"),
                    ("COMMITMENT", "Commitment"),
                    ("BOOKS", "Books"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
