# Generated by Django 5.0.4 on 2025-04-21 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_academicsession"),
        ("payments", "0002_remove_payment_message_alter_payment_purpose_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_by",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.AddField(
            model_name="payment",
            name="academic_session",
            field=models.ForeignKey(
                default=0.9945919370698132,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.academicsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="class_enrolled",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.class",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RegistrationPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeeAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Registration"),
                            ("COMMITMENT", "Commitment"),
                            ("BOOKS", "Books"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.academicsession",
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.class"
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "student_class", "purpose")},
            },
        ),
    ]
