# Generated by Django 5.0.4 on 2025-04-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_payment_amount_remove_payment_paid_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="class_enrolled",
            new_name="student_class",
        ),
    ]
