# Generated by Django 5.0.4 on 2024-06-19 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userprofile_verified_user_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=255, null=True)),
                ("faculty", models.CharField(blank=True, max_length=250, null=True)),
                ("department", models.CharField(blank=True, max_length=250, null=True)),
                ("matric_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("100", "100"),
                            ("200", "200"),
                            ("300", "300"),
                            ("400", "400"),
                            ("500", "500"),
                            ("600", "600"),
                            ("700", "700"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "hall_of_residence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("room_no", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
