# Generated by Django 5.0.4 on 2024-06-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_adminprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="approved",
            new_name="is_approved",
        ),
    ]
