# Generated by Django 5.0.4 on 2024-06-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_approved_user_is_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="verified",
            new_name="is_verified",
        ),
    ]
