# Generated by Django 5.0.4 on 2024-06-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_class_class_level"),
        ("users", "0009_rename_verified_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="student_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.class",
            ),
        ),
    ]
