# Generated by Django 5.0.4 on 2024-06-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_class_class_level"),
        ("users", "0010_studentprofile_student_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="student_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="core.class",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("tutor", "Tutor"), ("student", "Student")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="AdminProfile",
        ),
    ]
