# Generated by Django 5.0.4 on 2025-04-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_studentprofile_student_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="paid_reg",
            field=models.BooleanField(default=False),
        ),
    ]
