# Generated by Django 5.0.4 on 2025-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_auth_provider_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="auth_provider",
            new_name="primary_auth_provider",
        ),
        migrations.AddField(
            model_name="user",
            name="linked_auth_provider",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
