# Generated by Django 5.0.4 on 2025-04-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_rename_auth_provider_user_primary_auth_provider_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="linked_auth_provider",
            new_name="linked_auth_providers",
        ),
    ]
