# Generated by Django 5.0.4 on 2025-04-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="room_no",
        ),
    ]
