# Generated by Django 5.0.4 on 2024-06-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="recipient",
            field=models.CharField(
                blank=True,
                choices=[("tutors", "Tutors"), ("students", "Students")],
                max_length=255,
                null=True,
            ),
        ),
    ]
