# Generated by Django 5.0.4 on 2024-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_announcement_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="recipient",
            field=models.CharField(
                blank=True,
                choices=[("tutor", "Tutor"), ("student", "Student")],
                max_length=255,
                null=True,
            ),
        ),
    ]
